### PR TITLE
Complete Contactus from Html-css module

### PR DESCRIPTION
**Pull request by Ayushjain373**
Hey, @meerhamzadev  Thankyou for this opportunity. I just completed my part. I tried to design the contact page please review. If there are any changes please fell free to message me.
Thankyou
Ayush

### CODE REVIEW

**Comment by meerhamzadev** [comment]
Great, can you please add a screenshot?

**Comment by Ayushjain373** [comment]
Screenshot (174)

**Comment by meerhamzadev** [comment]
Ok great work.

**Comment by Ayushjain373** [comment]
Thankyou sir

**Pull request merged**
