### PR TITLE
Created Module/home page

### PR DESCRIPTION
**Pull request by sumitkr2000**
Hey @meerhamzadev I have created an awesome home page template please have a look at it. I have attached screenshot for a better view. 

Screenshot (347)

I hope that you will be happy with this home page and merge my pr. please add hacktoberfest-accepted label to it. Thank you!

### CODE REVIEW

**Comment by sumitkr2000** [comment]
@meerhamzadev Hope you like it :)

**Comment by sumitkr2000** [comment]
@meerhamzadev  you can see the site deployed here:-

https://sumitkr2000.github.io/Hacktoberfest-1/HTML-CSS/index.html

**Comment by meerhamzadev** [comment]
Great you really put effort in this contribution. I appreciate your dedication ❤️

**Comment by sumitkr2000** [comment]
Thank you @meerhamzadev !

**Pull request merged**
